# Default values for devops-in-a-box.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

git:
  token: ""
  username: ""
  password: ""
  server: "https://gitlab.com"
  
docker:
  server: "https://quay.io"
  username: ""
  password: ""
  
prometheus:
  token: ""

nameOverride: ""
fullnameOverride: ""
