# Default values for devops-in-a-box.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

git:
  username: ""
  password: ""
  server: "https://gitlab.com"
  
config:
  repoUrl: ""
  repoPath: ""
  
prometheus:
  token: ""
  
destination:
  namespace: ""

nameOverride: ""
fullnameOverride: ""
