{{- $fullName := include "devops-in-a-box.fullname" . -}}
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: {{ $fullName }}
  namespace: openshift-logging
  labels:
    app.kubernetes.io/component: cluster-logging
{{ include "devops-in-a-box.labels" . | indent 4 }}
spec:
  inputs: 
    - name: springBootLogs
      application:
        selector:
          matchLabels:
            perficient_com/runtime: spring-boot
  outputDefaults:
    elasticsearch:
      structuredTypeKey: kubernetes.container_name
  pipelines:
    - inputRefs:
        - springBootLogs
      name: spring-boot-logs
      outputRefs:
        - default
      parse: json
    - inputRefs:
        - application
      outputRefs:
        - default